# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd


class display(object):
    """Display HTML representation of multiple objects"""
    
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [6]:
df = pd.read_csv("/Users/jorgeshz/Data Science Bootcamp/DS-Repo-JorgeSanchez/02_Herramientas_Avanzadas/02_Pandas/02_Practica/04_Apply/Students_Alcohol_Consumption/student_mat.csv")

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [ ]:
df = df.loc[:, slice('school', 'guardian')]
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that will capitalize strings.

In [ ]:
capitalize_function = lambda x: x.capitalize()

'Jola '

### Step 6. Capitalize both Mjob and Fjob

In [ ]:
df['Mjob'] = df['Mjob'].str.capitalize()
df['Fjob'] = df['Fjob'].str.capitalize()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 7. Print the last elements of the data set.

In [14]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [ ]:
df['reason'] = df['reason'].str.capitalize()
df['guardian'] = df['guardian'].str.capitalize()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,Course,Mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,Course,Father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,Other,Mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,Home,Mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,Home,Father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,Course,Other
391,MS,M,17,U,LE3,T,3,1,Services,Services,Course,Mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,Course,Other
393,MS,M,18,R,LE3,T,3,2,Services,Other,Course,Mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,Course,Father

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [22]:
def majority(age):
    return age > 17

df['Legal_drinker'] = df['Age'].apply(majority)

In [21]:
df

,School,Sex,Age,Address,Famsize,Pstatus,Medu,Fedu,Mjob,Fjob,Reason,Guardian,Legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,Course,Mother,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,Course,Father,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,Other,Mother,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,Home,Mother,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,Home,Father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,Course,Other,True
391,MS,M,17,U,LE3,T,3,1,Services,Services,Course,Mother,False
392,MS,M,21,R,GT3,T,1,1,Other,Other,Course,Other,True
393,MS,M,18,R,LE3,T,3,2,Services,Other,Course,Mother,True
394,MS,M,19,U,LE3,T,1,1,Other,At_home,Course,Father,True

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [27]:
df.map(lambda x: x*10 
            if isinstance(x, (int, float)) 
            and not isinstance(x, bool)
            else x)

,School,Sex,Age,Address,Famsize,Pstatus,Medu,Fedu,Mjob,Fjob,Reason,Guardian,Legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,Course,Mother,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,Course,Father,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,Other,Mother,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,Home,Mother,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,Home,Father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,Course,Other,True
391,MS,M,170,U,LE3,T,30,10,Services,Services,Course,Mother,False
392,MS,M,210,R,GT3,T,10,10,Other,Other,Course,Other,True
393,MS,M,180,R,LE3,T,30,20,Services,Other,Course,Mother,True
394,MS,M,190,U,LE3,T,10,10,Other,At_home,Course,Father,True