# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [15]:
import pandas as pd 
import numpy as np 
import random as random

class display(object):
    """Display HTML representation of multiple objects"""
    
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [18]:
series1 = pd.DataFrame(np.random.randint(1, 5, size= 100).tolist())
series2 = pd.DataFrame(np.random.randint(1, 4, size=100).tolist())
series3= pd.DataFrame(np.random.randint(10000,30001, size=100).tolist())

### Step 3. Let's create a DataFrame by joinning the Series by column

In [12]:
df = pd.concat([series1, series2, series3], axis=1)

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [13]:
df.columns = ["bedrs", "bathrs", "price_sqr_meter"]

In [19]:
display('df')

df
    bedrs  bathrs  price_sqr_meter
0       2       1            28329
1       4       3            16224
2       3       1            15028
3       3       2            19994
4       1       2            15685
..    ...     ...              ...
95      1       3            25994
96      4       3            19983
97      4       3            17068
98      2       2            26836
99      1       1            19709

[100 rows x 3 columns]

### Step 5. Create a column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [ ]:
bigcolumn = pd.concat([series1, series2, series3], axis=0)

        0
95  18886
96  26447
97  23982
98  16867
99  28362

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [ ]:
print(bigcolumn) #Sí

        0
0       4
1       4
2       3
3       2
4       3
..    ...
95  18886
96  26447
97  23982
98  16867
99  28362

[300 rows x 1 columns]

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [26]:
bigcolumn.reset_index(drop=True)

         0
0        4
1        4
2        3
3        2
4        3
..     ...
295  18886
296  26447
297  23982
298  16867
299  28362

[300 rows x 1 columns]